### ISSUE TITLE
Error with a line in Win10 Home using the python scripts as-is.

### ISSUE THREAD

**Issue by shyamalschandra** [deepdrive/deepdrive#1]
Hi,

I received an error with the following line in Windows 10 Home using the python script as-is:

https://github.com/deepdrive/deepdrive/blob/master/install.py#L68

Somehow, the command-line argument for main.py doesn't exist in the main.py file.

Is there some sort of update missing?  Just curious...  I just want to make sure everything is up-to-date.

**Comment by crizCraig** [comment]
Hi @shyamalschandra - sorry about that. We recently changed that arg's name. Try now!

**Comment by shyamalschandra** [comment]
Thank you!
