### ISSUE TITLE
Scene segmentation in deepdrive

### ISSUE THREAD

**Issue by sourav-roni** [deepdrive/deepdrive#15]
Is there a way to get the scene segmentation directly from the simulator, or do we need to use an external segmentation model to predict the segmentation ?

**Comment by crizCraig** [comment]
Hi Sourav, we don't, but it would be fairly straightforward in Unreal with a [material](https://docs.unrealengine.com/en-us/Engine/Rendering/Materials) that colors meshes based on their segmentation class.

**Comment by sourav-roni** [comment]
Hi Craig, thanks a lot. I will try out the above approach!!

**Comment by crizCraig** [comment]
Sounds good. Let me know if you want me to look into the details some more or if you run into any issues.

**Comment by raks097** [comment]
@sourav-roni 
Hi,
Where you able to get it to work?

**Comment by sourav-roni** [comment]
@raks097 we used an external scene segmentation method
