### ISSUE TITLE
deepdrive_client

### ISSUE THREAD

**Issue by Nickhodem** [deepdrive/deepdrive#2]
Hi,
I had a lot of errors running "python install.py" I could handle it, but I got stuck in error 
`ImportError: No module named 'deepdrive_client'`
Where can I find this module?
Thanks for help. I can't wait to start up deepdrive!

**Comment by Nickhodem** [comment]
Ok, I got this... my mistake! Sorry!

**Comment by crizCraig** [comment]
@Nickhodem - Glad to hear you got it up and running. Please let us know if there is anything we can do to make the install process smoother.

**Comment by rootally** [comment]
Facing the same issue, how did you resolve it @Nickhodem ?

**Comment by udisamuel** [comment]
Hi, im having the same issue but cant seem to work it out
