### ISSUE TITLE
HDF5 to video format

### ISSUE THREAD

**Issue by federicomassa** [deepdrive/deepdrive#24]
Is there a standard way to convert the camera recording from hdf5 to a video format? I tried to google for solutions but I only found some custom solutions that seemed overly complicated for such a simple (maybe not?) task...

**Comment by crizCraig** [comment]
Hi @federicomassa - You could use the [read_hdf5](https://github.com/deepdrive/deepdrive/blob/master/utils.py#L105-L122) function to save to images and convert those to a video. You may need to add the [mean pixel](https://github.com/deepdrive/deepdrive/blob/cd1808285f492e1966d88751e33bb9ff20df96f0/config.py#L17) back. Should be just:

```
img += MEAN_PIXEL
```

**Comment by federicomassa** [comment]
Thank you very much, this solved the issue!
