### ISSUE TITLE
How do you pause (or do fixed-time steps) with the python gym API?

### ISSUE THREAD

**Issue by ihexx** [deepdrive/deepdrive#29]
Hi, I notice that when I run the example.py script in master, the simulator doesn't run synchronously with python.

I want to train an RL agent on each time step, and I want the simulator to pause while the model updates so it doesn't crash into a wall

**Comment by ihexx** [comment]
Is there some config step I'm missing?

**Comment by crizCraig** [comment]
Hi @ihexx ! Unfortunately synchronous stepping is not available in 2.0. Please check the `v3` branch https://github.com/deepdrive/deepdrive/blob/v3/example_sync.py or [this canonical link for posterity](https://github.com/deepdrive/deepdrive/blob/bbc483f6a79db712bff57b386a08b3cf5203e296/example_sync.py) for synchronous stepping.

**Comment by ihexx** [comment]
Ah I see, thank you.
I've switched to that branch and redid the install, but I'm having trouble running that script however. Here's a bit of the traceback:

>   File "E:\Projects\BOOM\Simulators\DeepDrive\API\util\ensure_sim.py", line 123, in get_sim_url
>     'in bucket %s' % (bucket_search_str, c.BUCKET_URL))
> RuntimeError: Could not find a sim version matching sim/deepdrive-sim-windows-3.0 in bucket https://s3-us-west-1.amazonaws.com/deepdrive

It was complaining of a duplicate simulator earlier, so I deleted the previous deepdrive simulator files from my home directory, and I used a fresh anaconda environment and redid the install, but it's still stuck on this

**Comment by crizCraig** [comment]
Hmm, so we only have the Linux versions up right now. Sorry about that, I will see if we can get you a Windows version, asap.

**Comment by ihexx** [comment]
Ah I see, thanks. In the mean time I'll spin up a linux machine and try it out
