### ISSUE TITLE
How can I download training data from AWS?

### ISSUE THREAD

**Issue by SpencerLo-CMU** [deepdrive/deepdrive#3]
Thanks for the awesome works!

I am now trying to train my own model in this platform. The first step is to download the training data from AWS.

After I use `aws s3 sync s3://deepdrive/data/baseline .`, it shows `fatal error: Unable to locate credentials` .

I am curious what kind of `access_key` and `secret_key` I need to use here.

**Comment by crizCraig** [comment]
Thanks @SpencerLo-CMU - Yeah there's some weirdness here I forgot to document. https://github.com/aws/aws-cli/issues/904 You can use any credentials or pass `--no-sign-request --region=us-west-1`
