### ISSUE TITLE
How to train the agent by myself?

### ISSUE THREAD

**Issue by XiChen918** [deepdrive/deepdrive#37]
Hi,

Thanks for the wonderful project you guys created.
A quick question, is there any way that I can start training by myself instead of using the dataset you provide? I'm trying to train it via Reinforcement Learning.
I tried the command "python main.py --train", but this command seems to need recorded data.

Thanks.

**Comment by XiChen918** [comment]
Thanks, should pay more attention to the description.

**Comment by crizCraig** [comment]
No worries @XiChen918. Happy training!
