### ISSUE TITLE
Data collection using the Simulator

### ISSUE THREAD

**Issue by sourav-roni** [deepdrive/deepdrive#4]
How do I save the frames and other data if I want to generate data by using the simulator.

**Comment by crizCraig** [comment]
Hi @sourav-roni ```python main.py --record``` will record the dataset for training the baseline agent. In general, to record, pass `should_record=True` to the `agent.py` contstructor. The recording functionality should actually be in `deepdrive_gym_env` so multiple agents can use it, but that's a different issue I guess :)
