### ISSUE TITLE
Cannot run PPO baseline

### ISSUE THREAD

**Issue by subhash** [deepdrive/deepdrive#42]
When I run
```
python main.py   --map kevindale_bare  -v --scenario=1 --ppo-baseline
```
the agent defaults to `mnet2 dagger`, but when I include the `agent` arg
```
python main.py   --map kevindale_bare  -v --scenario=1 --ppo-baseline --agent bootstrapped_ppo2
```
the map and scenario change over to the default `canyons`. 

What am I doing wrong here?

**Comment by subhash** [comment]
I dug some more and found that the problem is deeper than that. The switch `--ppo-baseline` simply does not work. I had to make two changes to get it to work:

Change default for `--agent` to `None` in `main.py`:
```
    args.add_agent_arg(
        '--agent', nargs='?', default=None,
        help='Agent type (%s, %s, %s)' % (c.DAGGER,
                                          c.DAGGER_MNET2,
                                          c.BOOTSTRAPPED_PPO2))
```

and correct the baseline weights dir in `runtime.py`:
```
PPO_BASELINE_WEIGHTS_DIR = os.path.join(WEIGHTS_DIR,
                                        os.path.join('ppo_baseline_agent_weights', 'checkpoints'))
```

@crizCraig Can you confirm if I am doing the right thing here? If yes, I am happy to send a PR to get this fixed

**Comment by crizCraig** [comment]
Hi @subhash - thanks for pointing this out. The following should now work to run the PPO baseline in Kevindale

```
python main.py --ppo-baseline --map=kevindale
```

**Comment by crizCraig** [comment]
With regards to resuming training, you can use the `--resume_train` parameter.

**Comment by subhash** [comment]
Thanks @crizCraig, I managed to run the PPO baseline (had to still include the config param `PPO_RESUME_PATH` because the ppo agent does not yet recognize `resume_train`)

Here's the result on `kevindale_bare, scenario 2`. Is this the expected level of performance the latest baseline is at? I understand that the challenge is in tuning it, but want to make sure I am seeing the correct baseline

![ppo](https://user-images.githubusercontent.com/87746/69937862-d28fa000-1501-11ea-814d-8dee1c6346a4.gif)

**Comment by crizCraig** [comment]
Hi @subhash - yes that looks expected. It's only trained on Canyons which is why it's not staying in the lane :)

**Comment by subhash** [comment]
@crizCraig Thanks, makes sense. Otherwise, you wouldn't call it a challenge, would you? :smile:
