### ISSUE TITLE
so what happend to the gtav version?

### ISSUE THREAD

**Issue by hydrogenpi** [deepdrive/deepdrive#5]
can the network weights for that be released

**Comment by crizCraig** [comment]
Unfortunately, we are unable to use GTAV for legal reasons. However, the latest weights and training regime are actually a lot further along, performance wise, than the GTAV version as we train with multiple camera viewpoints and different render backends (mixing DirectX and OpenGL from Windows and Linux respectively). Also, the procedure for randomizing actions for data collection is now automated so you can reproduce the experiment yourself and improve upon it. Additionally, the new simulation can do up to 8 cameras whereas GTA could only give us one (plus we give you the depth buffer which was not easily accessible in GTAV at the rate we do now via shared memory). Also for reinforcement learning, we synchronize steps which again was not something that folks were able to figure out how to do in GTAV in realtime. You'd get a frame like every few seconds. So all in all, I'd say we're a lot better off not using GTAV, although it was a cool way to start, having complete source access and control of the simulation are worlds apart.
