### ISSUE TITLE
Can't control the vehicle manually

### ISSUE THREAD

**Issue by foromer4** [deepdrive/deepdrive#8]
Thank you for this cool simulator!
I'm not able to control the vehicle steering in any of the run modes I tried.
I can give it commands through the python client, but when I try to do it directly on the 
running window it just doesn't respond. Some of the command like 'p' for pause do work-
so it's not that the app is stuck or anything like that.

**Comment by crizCraig** [comment]
Hi Omer, are you able to press <kbd>m</kbd> to control the car manually? <kdd>p</kpd> may only work in the Unreal Editor, but <kbd>Esc</kbd> should work to pause otherwise.

**Comment by crizCraig** [comment]
Pretty sure that <kbd>m</kbd> is what you need as I left it out of the README.md. Sorry about that. Closing for now.

**Comment by foromer4** [comment]
Thank you - "m" did the trick. would you like me the do a  PR with that fix to the documentation?

**Comment by crizCraig** [comment]
Hi Omer, should be fixed already. Thanks though!
